sources:
  # ... (tus fuentes actuales)

  # --- Gastronomía (scraping directo) ---
  - {name: Gastroeconomy (scraped), url: scrape:gastroeconomy, category: Gastronomía}
  - {name: El Comidista (scraped), url: scrape:elcomidista, category: Gastronomía}
