sources:
  # --- Gastronomía (España + Global, foco tendencias) ---
  - {name: Gastroeconomy (scraped), url: scrape:gastroeconomy, category: Gastronomía}
  - {name: El Comidista (scraped), url: scrape:elcomidista, category: Gastronomía}
  - {name: 50 Best (Stories), url: scrape:50best, category: Gastronomía}
  - {name: Michelin Guide – News & Views, url: scrape:michelin, category: Gastronomía}

  # Aquí puedes añadir tus otras categorías (Moda, Música, Arte/Diseño, Lifestyle, Hospitality) con RSS normales
  # Ejemplo:
  # - {name: The Guardian – Fashion, url: https://www.theguardian.com/fashion/rss, category: Moda}
