sources:
  # Ejemplos (ajusta a tus fuentes reales)
  - {name: Gastroeconomy (scraped), url: scrape:gastroeconomy, category: Gastronomía}
  - {name: The Guardian – Fashion, url: https://www.theguardian.com/fashion/rss, category: Moda}
  - {name: Dezeen, url: https://www.dezeen.com/feed/, category: Arte/Diseño}
  - {name: Skift, url: https://skift.com/feed, category: Hospitality}
